---
php_packages:
  - libmcrypt-devel
  - php
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-mbstring
  - php-mcrypt
  - php-mysql
  - php-pdo
  - php-pear
  - php-xml
php_ini:
  - { section: "Date", option: "date.timezone", value: "Asia/Tokyo" }
  - { section: "mail function", option: "mail.add_x_header", value: "Off" }
  - { section: "PHP", option: "expose_php", value: "Off" }
  - { section: "PHP", option: "max_execution_time", value: "120" }
  - { section: "PHP", option: "max_input_time", value: "180" }
  - { section: "PHP", option: "max_input_vars", value: "3000" }
  - { section: "PHP", option: "memory_limit", value: "2048M" }
  - { section: "PHP", option: "post_max_size", value: "16M" }
  - { section: "PHP", option: "upload_max_filesize", value: "128M" }
  - { section: "Session", option: "session.gc_maxlifetime", value: "10800" }
  - { section: "Session", option: "session.save_path", value: '"/var/lib/php/session"' }
